### ISSUE TITLE
CUPS_USER_ADMIN / CUPS_USER_PASSWORD not working..Unable to login to the admin interface

### ISSUE THREAD

**Issue by ropelletier** [SickHub/docker-cups-airprint#84]
```
services:
    airprint-bridge:
        network_mode: host
        container_name: cups-test
        environment:
            - CUPS_WEBINTERFACE=yes
            - CUPS_REMOTE_ADMIN=yes
            - CUPS_USER_ADMIN=admin
            - CUPS_USER_PASSWORD=password
        image: drpsychick/airprint-bridge:latest
```

When I try to login using the defined username and password or using root, I get access denied.
